In [36]:
import numpy as np
import scipy
import matplotlib as mat
from matplotlib import pyplot as plt
import sklearn
import pandas as pd

In [40]:
from sklearn import model_selection

from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC

from sklearn.metrics import classification_report
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix

In [33]:
#load dataset
nameDataset = "iris.txt"
nameFeatures = ['len_sepal','width_sepal','len_petal','width_petal','class']
df = pd.read_csv(nameDataset,names=nameFeatures) # returns a dataframe
print(df.head())
## ?? read more abt options in read_csv

   len_sepal  width_sepal  len_petal  width_petal        class
0        5.1          3.5        1.4          0.2  Iris-setosa
1        4.9          3.0        1.4          0.2  Iris-setosa
2        4.7          3.2        1.3          0.2  Iris-setosa
3        4.6          3.1        1.5          0.2  Iris-setosa
4        5.0          3.6        1.4          0.2  Iris-setosa


In [15]:
print(df.shape)

(150, 5)


In [16]:
print(df.describe())

        len_sepal  width_sepal   len_petal  width_petal
count  150.000000   150.000000  150.000000   150.000000
mean     5.843333     3.054000    3.758667     1.198667
std      0.828066     0.433594    1.764420     0.763161
min      4.300000     2.000000    1.000000     0.100000
25%      5.100000     2.800000    1.600000     0.300000
50%      5.800000     3.000000    4.350000     1.300000
75%      6.400000     3.300000    5.100000     1.800000
max      7.900000     4.400000    6.900000     2.500000


In [17]:
data = df.values # returns lowest common denominator dtype
print(data[0:9]) # converted to 2-d array

[[5.1 3.5 1.4 0.2 'Iris-setosa']
 [4.9 3.0 1.4 0.2 'Iris-setosa']
 [4.7 3.2 1.3 0.2 'Iris-setosa']
 [4.6 3.1 1.5 0.2 'Iris-setosa']
 [5.0 3.6 1.4 0.2 'Iris-setosa']
 [5.4 3.9 1.7 0.4 'Iris-setosa']
 [4.6 3.4 1.4 0.3 'Iris-setosa']
 [5.0 3.4 1.5 0.2 'Iris-setosa']
 [4.4 2.9 1.4 0.2 'Iris-setosa']]


In [18]:
print(data[140:]) # all rows after 2nd

[[6.7 3.1 5.6 2.4 'Iris-virginica']
 [6.9 3.1 5.1 2.3 'Iris-virginica']
 [5.8 2.7 5.1 1.9 'Iris-virginica']
 [6.8 3.2 5.9 2.3 'Iris-virginica']
 [6.7 3.3 5.7 2.5 'Iris-virginica']
 [6.7 3.0 5.2 2.3 'Iris-virginica']
 [6.3 2.5 5.0 1.9 'Iris-virginica']
 [6.5 3.0 5.2 2.0 'Iris-virginica']
 [6.2 3.4 5.4 2.3 'Iris-virginica']
 [5.9 3.0 5.1 1.8 'Iris-virginica']]


In [19]:
print(data[140:,-1]) # last column of rows after 140

['Iris-virginica' 'Iris-virginica' 'Iris-virginica' 'Iris-virginica'
 'Iris-virginica' 'Iris-virginica' 'Iris-virginica' 'Iris-virginica'
 'Iris-virginica' 'Iris-virginica']


In [20]:
df.groupby('class').size()


class
Iris-setosa        50
Iris-versicolor    50
Iris-virginica     50
dtype: int64

In [21]:
#divide into training and test data
# Y of training data has class and X has rest of columns
# Similarly Y of test data has class and X has rest of columns
X = data[:,0:-1] # all rows without the class attribute
Y = data[:,-1]  # all rows with the class attribute
print(X[0:9])
print(Y[0:9])

[[5.1 3.5 1.4 0.2]
 [4.9 3.0 1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.0 3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.0 3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]]
['Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa']


In [22]:
Val_size = 0.20
random_seed = 3
X_train,X_test,Y_train, Y_test = model_selection.train_test_split(X,Y,test_size = Val_size,random_state=random_seed)


In [32]:
deciTree = DecisionTreeClassifier()
deciTree.fit(X_train, Y_train)
predictions = deciTree.predict(X_test)
print("Accuracy on the Test Data ")
print(accuracy_score(Y_test, predictions))
#print(confusion_matrix(Y_validation, predictions))
print()
print()
print("Clasification Report on the Test Data")
print(classification_report(Y_test, predictions))

Accuracy on the Test Data 
0.966666666667


Clasification Report on the Test Data
                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        10
Iris-versicolor       1.00      0.90      0.95        10
 Iris-virginica       0.91      1.00      0.95        10

    avg / total       0.97      0.97      0.97        30



In [23]:
#Evaluation metric
eval = 'accuracy'

seed = 4
# Run the Decision Tree Classifier
model = DecisionTreeClassifier()

#use k cross validation
kfold = model_selection.KFold(n_splits=5, shuffle=True, random_state=seed) #shuffle the data 

#Run the classifier
results = model_selection.cross_val_score(model, X_train, Y_train, cv=kfold, scoring=eval)

#print evaluation metric for each fold
print(results) 

#print mean of the evaluation metric
metricResult= results.mean()
print(metricResult)

[ 1.          0.91666667  0.95833333  0.875       0.875     ]
0.925


In [43]:
seed = 4
models = []
models.append(('KNN', KNeighborsClassifier()))
models.append(('CART', DecisionTreeClassifier()))
models.append(('SVM', SVC()))

scoring = 'accuracy'
# evaluate each model in turn
results = []

for name, model in models:
	kfold = model_selection.KFold(n_splits=10, shuffle=True, random_state=seed)
	algo_result = model_selection.cross_val_score(model, X_train, Y_train, cv=kfold, scoring=scoring)
	results.append(algo_result)
	str = "%s: %f" % (name, algo_result.mean())
	print(str)

KNN: 0.966667
CART: 0.925000
SVM: 0.966667


In [45]:
classifier = KNeighborsClassifier()
classifier.fit(X_train, Y_train)
predictions = classifier.predict(X_test)
print("Accuracy on the Test Data ")
print(accuracy_score(Y_test, predictions))
#print(confusion_matrix(Y_validation, predictions))
print()
print()
print("Clasification Report on the Test Data")
print(classification_report(Y_test, predictions))

Accuracy on the Test Data 
0.966666666667


Clasification Report on the Test Data
                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        10
Iris-versicolor       1.00      0.90      0.95        10
 Iris-virginica       0.91      1.00      0.95        10

    avg / total       0.97      0.97      0.97        30

